# Generated by Django 4.2.8 on 2023-12-20 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0005_usermoduleprofile_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rolewithmoduleactionmap',
            old_name='module_role_map',
            new_name='module_action_map',
        ),
    ]
