class Module:
    ACTIVITY_LOG = 'Activity Log'
    USER = 'User'
    SCORECARD = 'ScoreCard'
    FEEDBACK = 'Feedback'
    ORGANIZATION = 'Organization'
    DASHBOARD = 'Dashboard'
    MEETING = 'Meeting'
    INDICATOR = 'Indicator'
    CONTENT = 'Content'
    CLINIC = 'Clinic'
    MONITOR_ACTION_PLAN = 'Monitor Action Plan'
    PERMISSION_CONTROL = 'Permission Control'
    PENDING_USER = 'Pending User'
