# Generated by Django 4.2.8 on 2023-12-20 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='location',
        ),
    ]
