# Generated by Django 4.2.8 on 2024-01-02 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_remove_clinic_location_clinicloc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='phone_number',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
