# Generated by Django 4.2.8 on 2024-02-16 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_alter_clinic_email_alter_clinic_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
