# Generated by Django 4.2.8 on 2024-01-01 12:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinic', '0002_remove_clinic_location_clinicloc'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync', models.TextField(blank=True, null=True)),
                ('meeting_level', models.CharField(choices=[('community_level', 'community_level'), ('service_provider_level', 'service_provider_level'), ('interface_level', 'interface_level')], max_length=50)),
                ('village_name', models.CharField(blank=True, max_length=255, null=True)),
                ('venue_name', models.CharField(blank=True, max_length=255, null=True)),
                ('meeting_status', models.CharField(choices=[('pending', 'pending'), ('completed', 'completed'), ('expired', 'expired')], max_length=255)),
                ('datetime', models.DateTimeField(blank=True, null=True)),
                ('uuid', models.CharField(max_length=255, unique=True)),
                ('community_clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.clinic')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_by_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_by_%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
