# Generated by Django 4.2.8 on 2024-01-02 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_action', '0002_meetingvalidation'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingvalidation',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
