# Generated by Django 4.2.8 on 2024-01-03 06:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meeting_action', '0004_parentmeeting_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync', models.TextField(blank=True, null=True)),
                ('meeting_level', models.CharField(choices=[('community_level', 'community_level'), ('service_provider_level', 'service_provider_level'), ('interface_level', 'interface_level')], max_length=50)),
                ('village_name', models.CharField(blank=True, max_length=255, null=True)),
                ('venue_name', models.CharField(blank=True, max_length=255, null=True)),
                ('meeting_status', models.CharField(choices=[('pending', 'pending'), ('completed', 'completed'), ('expired', 'expired')], max_length=255)),
                ('datetime', models.DateTimeField(blank=True, null=True)),
                ('uuid', models.CharField(max_length=255, unique=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_by_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meeting_action.parentmeeting')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_by_%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
