# Generated by Django 4.2.8 on 2024-01-23 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_action', '0009_actions'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingscoremain',
            name='uuid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
