# Generated by Django 4.2.8 on 2024-01-24 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_action', '0010_meetingscoremain_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentmeeting',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parentmeeting',
            name='is_active',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
