# Generated by Django 4.2.8 on 2024-01-24 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_action', '0011_parentmeeting_datetime_parentmeeting_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentmeeting',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
