# Generated by Django 4.2.8 on 2024-01-31 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_action', '0012_alter_parentmeeting_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='actions',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
